version: "3.8"

services:
  yolov7:
    build: .
    volumes:
      - ./data:/data
      - ./yolov7/runs:/yolov7/runs # path to your folder with weights and other results
    environment:
      - PYTHONUNBUFFERED=1
    command:
      [
        "train.py",
        "--data",
        "/data/dataset/data.yaml",
        "--weights",
        "/yolov7/runs/train/exp5/weights/best.pt",
        "--cfg",
        "cfg/training/yolov7.yaml",
        "--epochs",
        "100",
        "--img-size",
        "960",
        "--batch-size",
        "16",
      ] 
      # memory limit that you can set for the container
    shm_size: "48gb"
