services:
  yolov7:
    build: .
    volumes:
      # path to model directory containing model.yaml
      - <youryolomodel>:/model
      # path to training and validation data for model
      # NB: further (mounted) paths within this directory to be specified in model.yaml via `train` and `val` 
      - <yourmodeldata>:/data
      # path to yolov7 submodule (leave as is unless you have cloned yolov7 elsewhere)
      - ./yolov7/runs:/yolov7/runs
    environment:
      - PYTHONUNBUFFERED=1
    command:
      [
        "train.py",
        "--data",
        "/model/model.yaml",
        # "--weights",
        # "/yolov7/runs/train/exp5/weights/best.pt",
        "--cfg",
        "cfg/training/yolov7.yaml",
        "--epochs",
        "100",
        "--img-size",
        "960",
        "--batch-size",
        "16",
      ] 
      # memory limit that you can set for the container
    shm_size: "48gb"
