version: "3.8"

services:
  yolov7:
    build: .
    volumes:
      - ./data:/data
      - ./yolov7/runs:/yolov7/runs
    environment:
      - PYTHONUNBUFFERED=1
    command:
      [
        "detect.py",
        "--source",
        "/data/images", # path to your folder with images
        #"/data/video", # you can regognize objects in video files with this model too
        "--weights",
        "/yolov7/runs/train/exp6/weights/last.pt", # path to your weights file
        "--conf",
        "0.30",  # confidence threshold (default is 0.25)
  #     "--img-size",
  #     "640",
        "--save-txt", # save results to .txt - these will be your yolo coordinates files
        "--project", 
        "/data/results", # path to your folder for saving results
        "--name", 
        "output" # name of the output folder
      ]
      # memory limit that you can set for the container
    shm_size: "24gb"
